#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"
source steps/sync_steps.sh


function preconditions {
  sync_preconditions
}


function steps {
  sync_steps
}


run "$@"
